### ISSUE TITLE
Integrar Vue.js con Swan

### ISSUE THREAD

**Issue by sebastianserna** [swanix/ui#41]
[Vue.js](http://vuejs.org/) es la librería JavaScript que utilizaremos por defecto en Swan. Esta librería es potente, elegante y está teniendo mucha acogida por la comunidad de desarrolladores, por ejemplo ha sido elegida como la librería front-end por defecto del framework Laravel (que permite desarrollar aplicaciones web con el lenguaje PHP). 

Para integrarlo en Swan debemos reemplazar todos los archivos de JQuery presentes en la  [carpeta scripts](https://github.com/acuariux/swan/tree/master/scripts) que no tiene un orden riguroso porque hasta el momento me he concentrado principalmente en el código HTML y CSS. Sin embargo, es necesario reestructurarla para crear los componentes en Vue.js de una forma ordenada y que permita añadir módulos futuros.

Los componentes básicos en los que podemos concentrarnos para iniciar son:
- [ ] [Menú lateral (off-canvas)](#45)
- [ ] Menú básico con submenús
- [ ] [Scroll personalizado](#46)
- [ ] [Switch (ON / OFF)](#44)
- [ ] Dropdown (custom select)
- [ ] [Slideshow](#48)
- [ ] [Panel de pestañas](#47)

En el sitio [http://vuejsexamples.com/ ](http://vuejsexamples.com/)se listan ejemplos de componentes creados con Vue.js podemos revisarlos y decidir si utilizamos algunos.

**Comment by sebastianserna** [comment]
Este issue se traslada al proyecto swan-vue la nueva ubicación es:
https://github.com/acuariux/swan-vue/issues/1
